const allBatches = [
  // 第 1 批
  [
    { "english": "a schoolmate", "chinese": "一位同校同學", "sentence": "Tom is my schoolmate." },
    { "english": "a husband", "chinese": "一位先生 / 丈夫", "sentence": "Her husband is a teacher." },
    { "english": "a wife", "chinese": "一位太太 / 妻子", "sentence": "His wife is very kind." },
    { "english": "old", "chinese": "老的 / 舊的", "sentence": "My grandfather is very old." },
    { "english": "a year", "chinese": "一年", "sentence": "There are twelve months in a year." },
    { "english": "where", "chinese": "哪裡", "sentence": "Where is my book?" },
    { "english": "a classroom", "chinese": "一間教室", "sentence": "We read books in the classroom." },
    { "english": "here", "chinese": "這裡", "sentence": "Come here, please." },
    { "english": "home", "chinese": "家", "sentence": "I want to go home after school." },
    { "english": "right here", "chinese": "就在這裡", "sentence": "Your bag is right here." },
    { "english": "right there", "chinese": "就在那裡", "sentence": "The cat is right there." },
    { "english": "at", "chinese": "在", "sentence": "I am at school now." },
    { "english": "work", "chinese": "工作的地方", "sentence": "My dad goes to work every day." },
    { "english": "over here", "chinese": "這裡", "sentence": "Put the box over here." },
    { "english": "over there", "chinese": "那裡", "sentence": "Look at the bird over there." },
    { "english": "out", "chinese": "外出了 / 出去了", "sentence": "My mom is out now." },
    { "english": "to pick up", "chinese": "撿起來 / 拿起來", "sentence": "Please pick up the trash." },
    { "english": "to put down", "chinese": "放下", "sentence": "Put down your pencil and listen." },
    { "english": "next to", "chinese": "在...的旁邊", "sentence": "I sit next to my best friend." },
    { "english": "under", "chinese": "在...的下面", "sentence": "The dog is sleeping under the table." },
    { "english": "happy", "chinese": "快樂的", "sentence": "She is very happy today." },
    { "english": "sad", "chinese": "難過的 / 傷心的", "sentence": "He was sad because he lost his toy." },
    { "english": "an adjective", "chinese": "一個形容詞", "sentence": "The word \"happy\" is an adjective." },
    { "english": "a noun", "chinese": "一個名詞", "sentence": "The word \"apple\" is a noun." },
    { "english": "cute", "chinese": "可愛的", "sentence": "Look at that cute puppy!" },
    { "english": "ugly", "chinese": "醜陋的", "sentence": "The witch in the story is ugly." },
    { "english": "handsome", "chinese": "英俊的", "sentence": "The prince is very handsome." },
    { "english": "average", "chinese": "平均的 / 一般的", "sentence": "My math score is average." },
    { "english": "right", "chinese": "對的", "sentence": "Your answer is right!" },
    { "english": "wrong", "chinese": "錯的", "sentence": "This answer is wrong, please try again." }
  ],

  // 第 2 批
  [
    { "english": "tall", "chinese": "高的", "sentence": "My father is very tall." },
    { "english": "short", "chinese": "矮的 / 短的", "sentence": "My little sister is short." },
    { "english": "black", "chinese": "黑色", "sentence": "I have a black pen." },
    { "english": "white", "chinese": "白色", "sentence": "The clouds in the sky are white." },
    { "english": "blue", "chinese": "藍色", "sentence": "The ocean is beautiful and blue." },
    { "english": "red", "chinese": "紅色", "sentence": "Apples are usually red." },
    { "english": "green", "chinese": "綠色", "sentence": "Frogs and leaves are green." },
    { "english": "yellow", "chinese": "黃色", "sentence": "Bananas are yellow." },
    { "english": "orange", "chinese": "橘色", "sentence": "I like to eat orange carrots." },
    { "english": "brown", "chinese": "棕色 / 咖啡色", "sentence": "The bear in the zoo is brown." },
    { "english": "gold", "chinese": "金色", "sentence": "She wears a gold ring." },
    { "english": "silver", "chinese": "銀色", "sentence": "The coins in my pocket are silver." },
    { "english": "tan", "chinese": "黃褐色", "sentence": "He wore a tan hat in the sun." },
    { "english": "purple", "chinese": "紫色", "sentence": "Grapes are often purple." },
    { "english": "pink", "chinese": "粉紅色", "sentence": "Pigs are pink and cute." },
    { "english": "gray", "chinese": "灰色", "sentence": "Elephants are big and gray." },
    { "english": "light", "chinese": "淺色的", "sentence": "She likes to wear light colors." },
    { "english": "dark", "chinese": "深色的", "sentence": "He has dark brown hair." },
    { "english": "a jacket", "chinese": "一件夾克", "sentence": "Put on a jacket, it is cold outside." },
    { "english": "a shirt", "chinese": "一件襯衫 / 上衣", "sentence": "He is wearing a white shirt." },
    { "english": "hair", "chinese": "頭髮 / 毛", "sentence": "My sister has long black hair." },
    { "english": "a bicycle", "chinese": "一輛腳踏車", "sentence": "I ride a bicycle to the park." },
    { "english": "a grade", "chinese": "一個年級", "sentence": "I am in the fourth grade." },
    { "english": "first (1st)", "chinese": "第一", "sentence": "He won the first prize." },
    { "english": "second (2nd)", "chinese": "第二", "sentence": "She is the second student in line." },
    { "english": "third (3rd)", "chinese": "第三", "sentence": "My birthday is on the third of May." },
    { "english": "fourth (4th)", "chinese": "第四", "sentence": "This is my fourth piece of cake." },
    { "english": "fifth (5th)", "chinese": "第五", "sentence": "May is the fifth month of the year." },
    { "english": "sixth (6th)", "chinese": "第六", "sentence": "Saturday is the sixth day of the week." },
    { "english": "singular", "chinese": "單數的", "sentence": "The word 'apple' is a singular noun." },
    { "english": "plural", "chinese": "複數的", "sentence": "The word 'apples' is a plural noun." },
    { "english": "pretty", "chinese": "漂亮的", "sentence": "The flowers in the garden are pretty." },
    { "english": "irregular", "chinese": "不規則的", "sentence": "The word 'mice' is an irregular plural." },
    { "english": "people", "chinese": "人們", "sentence": "Many people are waiting for the bus." },
    { "english": "a child", "chinese": "一位孩子", "sentence": "A child is playing with a toy." },
    { "english": "children", "chinese": "孩子們", "sentence": "The children are singing happily." },
    { "english": "a man", "chinese": "一位男人", "sentence": "A man is driving the car." },
    { "english": "men", "chinese": "男人們", "sentence": "Two men are working in the office." },
    { "english": "a woman", "chinese": "一位女人", "sentence": "A woman is reading a book." },
    { "english": "women", "chinese": "女人們", "sentence": "Three women are drinking tea." }
  ],

  // 第 3 批
  [
    { "english": "a foot", "chinese": "一隻腳", "sentence": "I hurt my right foot today." },
    { "english": "feet", "chinese": "腳(複數)", "sentence": "Wash your feet before you go to bed." },
    { "english": "a tooth", "chinese": "一顆牙齒", "sentence": "I have a loose tooth." },
    { "english": "teeth", "chinese": "牙齒(複數)", "sentence": "Brush your teeth every morning and night." },
    { "english": "a mouse", "chinese": "一隻老鼠", "sentence": "A little mouse is hiding under the bed." },
    { "english": "loud", "chinese": "大聲的", "sentence": "The music is too loud." },
    { "english": "quiet", "chinese": "安靜的", "sentence": "Please be quiet in the library." },
    { "english": "mice", "chinese": "老鼠(複數)", "sentence": "Cats like to catch mice." },
    { "english": "(a) fish", "chinese": "魚", "sentence": "Look at that colorful fish in the water." },
    { "english": "an elementary school", "chinese": "一間小學", "sentence": "My sister goes to an elementary school." },
    { "english": "a junior high school", "chinese": "一間國中", "sentence": "My brother is a student at a junior high school." },
    { "english": "a senior high school", "chinese": "一間高中", "sentence": "He studies hard in a senior high school." },
    { "english": "young", "chinese": "年輕的", "sentence": "My little cousin is very young." },
    { "english": "tired", "chinese": "累的 / 疲倦的", "sentence": "I feel tired after running." },
    { "english": "energetic", "chinese": "有精神的", "sentence": "The puppy is very energetic and playful." },
    { "english": "new", "chinese": "新的", "sentence": "I have a new pair of shoes." },
    { "english": "a face", "chinese": "一張臉", "sentence": "Wash your face with warm water." },
    { "english": "a head", "chinese": "一顆頭", "sentence": "She is wearing a cute hat on her head." },
    { "english": "a forehead", "chinese": "一個額頭", "sentence": "He wiped the sweat from his forehead." },
    { "english": "an ear", "chinese": "一隻耳朵", "sentence": "The rabbit has one floppy ear." },
    { "english": "an eyebrow", "chinese": "一個眉毛", "sentence": "She raised her left eyebrow." },
    { "english": "an eye", "chinese": "一隻眼睛", "sentence": "He closed his right eye." },
    { "english": "a mouth", "chinese": "一張嘴巴", "sentence": "Open your mouth and say Ah." },
    { "english": "a chin", "chinese": "一個下巴", "sentence": "The boy has a small cut on his chin." },
    { "english": "a cheek", "chinese": "一個臉頰", "sentence": "She kissed her mother on the cheek." },
    { "english": "a nose", "chinese": "一個鼻子", "sentence": "My dog has a cold, wet nose." },
    { "english": "a lip", "chinese": "一片嘴唇", "sentence": "He bit his bottom lip." },
    { "english": "the sky", "chinese": "天空", "sentence": "The birds are flying in the sky." },
    { "english": "clean", "chinese": "乾淨的", "sentence": "Please keep your room clean." },
    { "english": "a tongue", "chinese": "一根舌頭", "sentence": "The lizard has a very long tongue." },
    { "english": "grass", "chinese": "草", "sentence": "The children are playing on the green grass." },
    { "english": "shy", "chinese": "害羞的", "sentence": "The little girl is too shy to talk." },
    { "english": "outgoing", "chinese": "外向的", "sentence": "My best friend is very outgoing and talks to everyone." },
    { "english": "lazy", "chinese": "懶惰的", "sentence": "The lazy cat sleeps all day." },
    { "english": "hard-working", "chinese": "努力的 / 用功的", "sentence": "Ants are very hard-working insects." },
    { "english": "nervous", "chinese": "緊張的", "sentence": "I feel nervous before the big test." },
    { "english": "confident", "chinese": "有自信的", "sentence": "She is confident that she will win the game." },
    { "english": "a kiss", "chinese": "一個親吻", "sentence": "Mommy gave me a goodnight kiss." },
    { "english": "a watch", "chinese": "一只手錶", "sentence": "My dad gave me a new watch for my birthday." },
    { "english": "a dish", "chinese": "一個盤子", "sentence": "Please put the cake on a dish." }
  ],

  // 第 4 批
  [
    { "english": "a wish", "chinese": "一個願望", "sentence": "Make a wish before you blow out the candles." },
    { "english": "stupid", "chinese": "愚笨的", "sentence": "It was a stupid mistake, but I learned from it." },
    { "english": "dirty", "chinese": "髒的", "sentence": "Wash your dirty hands before dinner." },
    { "english": "busy", "chinese": "忙碌的", "sentence": "My dad is very busy with his work today." },
    { "english": "now", "chinese": "現在", "sentence": "We need to leave for school right now." },
    { "english": "from", "chinese": "從 / 來自", "sentence": "This letter is from my grandmother." },
    { "english": "Taipei", "chinese": "台北", "sentence": "Taipei is a very big and busy city." },
    { "english": "Taiwan", "chinese": "台灣", "sentence": "We live in a beautiful place called Taiwan." },
    { "english": "the Republic of China", "chinese": "中華民國", "sentence": "The official name of our country is the Republic of China." },
    { "english": "the R.O.C.", "chinese": "中華民國", "sentence": "We celebrate the birthday of the R.O.C. on Double Tenth Day." },
    { "english": "healthy", "chinese": "健康的", "sentence": "Eating vegetables keeps your body healthy." },
    { "english": "sick", "chinese": "生病的", "sentence": "I have to stay in bed when I am sick." },
    { "english": "nice", "chinese": "好的 / 乖的", "sentence": "She is a very nice and polite girl." },
    { "english": "naughty", "chinese": "頑皮的", "sentence": "The naughty puppy chewed on my shoes." },
    { "english": "we", "chinese": "我們", "sentence": "We are going to the park together." },
    { "english": "diligent", "chinese": "勤勞的", "sentence": "The diligent student always finishes her homework on time." },
    { "english": "art", "chinese": "美術", "sentence": "I like drawing and painting in art class." },
    { "english": "a class", "chinese": "一個課程", "sentence": "We have a math class in the morning." },
    { "english": "computer class", "chinese": "電腦課", "sentence": "We learn how to type in computer class." },
    { "english": "Mandarin Chinese", "chinese": "國語 / 中文", "sentence": "We speak Mandarin Chinese at home." },
    { "english": "math", "chinese": "數學", "sentence": "Math is my favorite subject because I like numbers." },
    { "english": "music", "chinese": "音樂", "sentence": "We sing beautiful songs in music class." },
    { "english": "PE", "chinese": "體育", "sentence": "We run and play basketball in PE class." },
    { "english": "science", "chinese": "科學", "sentence": "We do cool experiments in science class." },
    { "english": "social studies", "chinese": "社會課", "sentence": "We learn about maps and history in social studies class." },
    { "english": "easy", "chinese": "容易的", "sentence": "This spelling test is very easy for me." },
    { "english": "difficult", "chinese": "困難的", "sentence": "This puzzle is a bit difficult to solve." },
    { "english": "hard", "chinese": "困難的", "sentence": "The math question is too hard, can you help me?" },
    { "english": "useful", "chinese": "有用的", "sentence": "A dictionary is a very useful book for learning English." },
    { "english": "useless", "chinese": "沒有用的", "sentence": "A broken pencil is useless if you cannot write with it." },
    { "english": "a subject", "chinese": "一個科目", "sentence": "Science is a very interesting subject." },
    { "english": "important", "chinese": "重要的", "sentence": "It is important to drink water every day." },
    { "english": "unimportant", "chinese": "不重要的", "sentence": "That small mistake is unimportant, don't worry about it." },
    { "english": "interesting", "chinese": "有趣的", "sentence": "This storybook about animals is very interesting." },
    { "english": "fun", "chinese": "好玩的", "sentence": "Playing games with my friends is so much fun." },
    { "english": "boring", "chinese": "令人無聊的", "sentence": "Waiting for the bus in the rain can be boring." },
    { "english": "an adult", "chinese": "一位大人 / 成人", "sentence": "You need an adult to help you cross the busy street." },
    { "english": "America", "chinese": "美國", "sentence": "He took a long airplane ride to America." },
    { "english": "the USA", "chinese": "美國", "sentence": "Washington, D.C. is the capital of the USA." },
    { "english": "Canada", "chinese": "加拿大", "sentence": "Canada is a very cold country in the winter." }
  ],

  // 第 5 批
  [
    { "english": "Australia", "chinese": "澳洲", "sentence": "Kangaroos and koalas live in Australia." },
    { "english": "England", "chinese": "英國", "sentence": "London is a very famous city in England." },
    { "english": "Japan", "chinese": "日本", "sentence": "My family wants to visit Japan and eat sushi." },
    { "english": "New Zealand", "chinese": "紐西蘭", "sentence": "There are many cute sheep in New Zealand." },
    { "english": "a country", "chinese": "一個國家", "sentence": "Taiwan is a beautiful country with yummy food." },
    { "english": "you (plural)", "chinese": "你們", "sentence": "Are you all ready for the spelling game?" },
    { "english": "friendly", "chinese": "友善的 / 親切的", "sentence": "My new classmate is very friendly and shares his toys." },
    { "english": "a pet", "chinese": "一隻寵物", "sentence": "I want to have a cute dog as a pet." },
    { "english": "a neighbor", "chinese": "一位鄰居", "sentence": "Our neighbor always says good morning to us." },
    { "english": "they", "chinese": "他們", "sentence": "They are playing basketball in the park." },
    { "english": "a body", "chinese": "一個身體", "sentence": "Eating vegetables is good for your body." },
    { "english": "a neck", "chinese": "一個脖子", "sentence": "A giraffe has a very long neck to eat leaves." },
    { "english": "a shoulder", "chinese": "一個肩膀", "sentence": "My dad carries me on his shoulder." },
    { "english": "a chest", "chinese": "一個胸部", "sentence": "The big gorilla beats its chest." },
    { "english": "a finger", "chinese": "一根手指", "sentence": "I have five fingers on my right hand." },
    { "english": "an arm", "chinese": "一隻手臂", "sentence": "She throws the ball with her strong arm." },
    { "english": "a leg", "chinese": "一隻腿", "sentence": "My left leg hurts a little bit after running." },
    { "english": "a back", "chinese": "一個背部", "sentence": "The old man's back hurts from carrying the heavy box." },
    { "english": "a knee", "chinese": "一個膝蓋", "sentence": "He fell down and scraped his knee." },
    { "english": "a brain", "chinese": "一個頭腦", "sentence": "Use your brain to solve this math puzzle." },
    { "english": "a heart", "chinese": "一顆心臟", "sentence": "Place your right hand over your heart." },
    { "english": "a stomach", "chinese": "一個胃 / 肚子", "sentence": "My stomach is very full after eating the big pizza." },
    { "english": "ready", "chinese": "準備好的", "sentence": "Are you ready to go to the zoo?" },
    { "english": "to learn", "chinese": "學習", "sentence": "We go to school to learn new things every day." },
    { "english": "to go", "chinese": "走 / 去", "sentence": "I want to go to the playground this afternoon." },
    { "english": "a home", "chinese": "一個家", "sentence": "A bird's nest is a safe home for baby birds." },
    { "english": "hot", "chinese": "熱的", "sentence": "Be careful, the soup is very hot!" },
    { "english": "cold", "chinese": "冷的", "sentence": "It is cold outside, so remember to wear a jacket." },
    { "english": "to take a test", "chinese": "考試", "sentence": "We will take a spelling test tomorrow morning." },
    { "english": "to answer", "chinese": "回答", "sentence": "Please raise your hand to answer the question." },
    { "english": "homework", "chinese": "功課", "sentence": "Don't forget to finish your math homework after dinner." },
    { "english": "time", "chinese": "時間", "sentence": "What time is it now?" },
    { "english": "a question", "chinese": "一個問題 / 題目", "sentence": "I have a question about the math homework." },
    { "english": "to ask", "chinese": "問", "sentence": "If you don't know the answer, you can ask the teacher." },
    { "english": "very", "chinese": "非常", "sentence": "Thank you very much for helping me clean the room." },
    { "english": "strong", "chinese": "強壯的", "sentence": "Elephants are very big and strong." },
    { "english": "weak", "chinese": "虛弱的", "sentence": "He felt weak after being sick for three days." },
    { "english": "a telephone", "chinese": "一個電話", "sentence": "The telephone is ringing in the living room." },
    { "english": "a number", "chinese": "一個數字 / 號碼", "sentence": "Seven is my lucky number." },
    { "english": "a phone", "chinese": "一個電話", "sentence": "My mom uses her phone to take pictures of me." }
  ],

  // 第 6 批
  [
    { "english": "a T-shirt", "chinese": "一件T恤", "sentence": "I wear a white T-shirt in summer." },
    { "english": "a sweater", "chinese": "一件毛衣", "sentence": "Put on a sweater, it is cold today." },
    { "english": "a dress", "chinese": "一件洋裝", "sentence": "She is wearing a beautiful pink dress." },
    { "english": "a skirt", "chinese": "一件裙子", "sentence": "The girl in the blue skirt is my friend." },
    { "english": "a vest", "chinese": "一件背心", "sentence": "My grandfather likes to wear a brown vest." },
    { "english": "a uniform", "chinese": "一件制服", "sentence": "We have to wear a school uniform every day." },
    { "english": "a jacket", "chinese": "一件夾克", "sentence": "He left his jacket on the chair." },
    { "english": "a coat", "chinese": "一件外套", "sentence": "It is snowing, so you need a heavy coat." },
    { "english": "a hat", "chinese": "一頂帽子", "sentence": "The sun is hot, please wear a hat." },
    { "english": "underwear", "chinese": "內褲", "sentence": "Remember to change your underwear every day." },
    { "english": "an animal", "chinese": "一隻動物", "sentence": "A lion is a very dangerous wild animal." },
    { "english": "our", "chinese": "我們的", "sentence": "Welcome to our new house!" },
    { "english": "a month", "chinese": "一個月", "sentence": "There are about four weeks in a month." },
    { "english": "January", "chinese": "一月", "sentence": "January is the first month of the year." },
    { "english": "February", "chinese": "二月", "sentence": "February is the shortest month of the year." },
    { "english": "March", "chinese": "三月", "sentence": "Spring usually begins in March." },
    { "english": "April", "chinese": "四月", "sentence": "We have a lot of spring rain in April." },
    { "english": "May", "chinese": "五月", "sentence": "Mother's Day is in May." },
    { "english": "June", "chinese": "六月", "sentence": "Summer vacation usually starts in June." },
    { "english": "July", "chinese": "七月", "sentence": "It is very hot and sunny in July." },
    { "english": "August", "chinese": "八月", "sentence": "August is the eighth month of the year." },
    { "english": "September", "chinese": "九月", "sentence": "We go back to school in September." },
    { "english": "October", "chinese": "十月", "sentence": "Halloween is in October." },
    { "english": "November", "chinese": "十一月", "sentence": "The weather gets cooler in November." },
    { "english": "December", "chinese": "十二月", "sentence": "Christmas is a happy holiday in December." },
    { "english": "seventh (7th)", "chinese": "第七", "sentence": "Sunday is the seventh day of the week." },
    { "english": "eighth (8th)", "chinese": "第八", "sentence": "He was the eighth student to finish the test." },
    { "english": "pants", "chinese": "長褲(複數)", "sentence": "He is wearing long blue pants." },
    { "english": "shorts", "chinese": "短褲(複數)", "sentence": "Boys like to wear shorts in the summer." },
    { "english": "shoes", "chinese": "鞋子(複數)", "sentence": "Take off your shoes before entering the house." },
    { "english": "socks", "chinese": "襪子(複數)", "sentence": "I need a clean pair of white socks." },
    { "english": "sandals", "chinese": "涼鞋(複數)", "sentence": "She wears sandals to the beach." },
    { "english": "glasses", "chinese": "眼鏡(複數)", "sentence": "My grandmother uses glasses to read books." },
    { "english": "large", "chinese": "大的", "sentence": "Elephants are very large animals." },
    { "english": "its", "chinese": "它的 / 牠的", "sentence": "The happy dog is wagging its tail." },
    { "english": "to drink", "chinese": "喝", "sentence": "I want to drink a glass of milk." },
    { "english": "a trunk", "chinese": "一個(大象的)鼻子", "sentence": "The elephant uses its trunk to drink water." },
    { "english": "a tail", "chinese": "一條尾巴", "sentence": "A monkey uses its long tail to climb trees." },
    { "english": "skin", "chinese": "皮膚", "sentence": "A frog has smooth and wet skin." },
    { "english": "long", "chinese": "長的", "sentence": "She has long and pretty black hair." }
  ],

  // 第 7 批
  [
    { "english": "fur", "chinese": "(動物的)毛", "sentence": "My pet cat has very soft fur." },
    { "english": "lucky", "chinese": "幸運的", "sentence": "I found a coin on the street, I am so lucky." },
    { "english": "unlucky", "chinese": "不幸運的", "sentence": "He was unlucky and lost his favorite toy." },
    { "english": "a pineapple", "chinese": "一顆鳳梨", "sentence": "I like to eat sweet and yellow pineapple." },
    { "english": "your (plural)", "chinese": "你們的", "sentence": "Please open your books and look at the blackboard." },
    { "english": "a giraffe", "chinese": "一隻長頸鹿", "sentence": "A giraffe has a long neck to eat leaves from trees." },
    { "english": "soft", "chinese": "軟的", "sentence": "This teddy bear is very soft and cute." },
    { "english": "a date", "chinese": "一個日期", "sentence": "Do you know the date of her birthday?" },
    { "english": "today", "chinese": "今天", "sentence": "Today is a beautiful and sunny day." },
    { "english": "to cook", "chinese": "煮", "sentence": "My mom is going to cook dinner for us." },
    { "english": "a bird", "chinese": "一隻鳥", "sentence": "A little blue bird is singing in the tree." },
    { "english": "to fly", "chinese": "飛", "sentence": "Birds can fly high in the blue sky." },
    { "english": "to dance", "chinese": "跳舞", "sentence": "She likes to sing and dance with her friends." },
    { "english": "to swim", "chinese": "游泳", "sentence": "We love to swim in the pool during summer." },
    { "english": "a thumb", "chinese": "一隻大拇指", "sentence": "Give me a thumbs up if you are ready!" },
    { "english": "to watch", "chinese": "觀看", "sentence": "Let's watch a cartoon in the living room." },
    { "english": "a movie", "chinese": "一部電影", "sentence": "We went to the theater to see a funny movie." },
    { "english": "to help", "chinese": "幫助", "sentence": "Can you help me clean the classroom?" },
    { "english": "to turn on", "chinese": "打開", "sentence": "Please turn on the light, it is too dark here." },
    { "english": "a banana", "chinese": "一根香蕉", "sentence": "Monkeys love to eat sweet bananas." },
    { "english": "a cup", "chinese": "一個杯子", "sentence": "I want to drink a cup of hot tea." },
    { "english": "soda", "chinese": "汽水", "sentence": "Drinking too much soda is bad for your teeth." },
    { "english": "a glass", "chinese": "一個玻璃杯子", "sentence": "Please give me a glass of cold water." },
    { "english": "milk", "chinese": "牛奶", "sentence": "Drinking milk helps you grow strong and tall." },
    { "english": "candy", "chinese": "糖果", "sentence": "Eating too much sweet candy will hurt your teeth." },
    { "english": "some", "chinese": "一些", "sentence": "I want some more water, I am very thirsty." },
    { "english": "to ride", "chinese": "騎", "sentence": "I like to ride my bicycle in the park." },
    { "english": "to drive", "chinese": "駕駛", "sentence": "My dad will drive us to the supermarket." },
    { "english": "a car", "chinese": "一輛汽車", "sentence": "They went to the beach by car." },
    { "english": "their", "chinese": "他們的", "sentence": "The students are doing their math homework." },
    { "english": "to write", "chinese": "寫", "sentence": "Use a black pencil to write your name here." },
    { "english": "to read", "chinese": "讀 / 看書", "sentence": "I like to read storybooks before going to bed." },
    { "english": "a newspaper", "chinese": "一份報紙", "sentence": "My grandpa reads a newspaper every morning." },
    { "english": "the United States", "chinese": "美國", "sentence": "They took a long airplane ride to the United States." },
    { "english": "Canadian", "chinese": "加拿大人 / 加拿大的", "sentence": "He is from Canada, so he is a Canadian." },
    { "english": "American", "chinese": "美國人 / 美國的", "sentence": "She is from the USA, so she is American." },
    { "english": "English", "chinese": "英國人 / 英國的 / 英文", "sentence": "We have an English class every Monday." },
    { "english": "Chinese", "chinese": "中國人 / 中國的 / 中文", "sentence": "We speak Chinese with our family at home." },
    { "english": "Japanese", "chinese": "日本人 / 日本的 / 日文", "sentence": "Sushi is a very famous Japanese food." },
    { "english": "Taiwanese", "chinese": "台灣人 / 台灣的 / 台語", "sentence": "Beef noodle soup is a yummy Taiwanese food." }
  ],

  // 第 8 批
  [
    { "english": "Australian", "chinese": "澳洲人 / 澳洲的", "sentence": "Koalas and kangaroos are Australian animals." },
    { "english": "Korean", "chinese": "韓國人 / 韓國的 / 韓文", "sentence": "I like to eat yummy Korean food." },
    { "english": "Thai", "chinese": "泰國人 / 泰國的 / 泰文", "sentence": "Elephants are very important in Thai culture." },
    { "english": "a seat", "chinese": "一個座位", "sentence": "Please find a seat and sit down." },
    { "english": "to play (a sport)", "chinese": "打 / 踢(球類運動)", "sentence": "I like to play basketball with my friends." },
    { "english": "a sport", "chinese": "一種球類運動", "sentence": "Baseball is a very popular sport in Taiwan." },
    { "english": "baseball", "chinese": "棒球", "sentence": "He hit the baseball very hard with a bat." },
    { "english": "basketball", "chinese": "籃球", "sentence": "Jeremy Lin is a great basketball player." },
    { "english": "tennis", "chinese": "網球", "sentence": "You need a racket to play tennis." },
    { "english": "badminton", "chinese": "羽毛球", "sentence": "We play badminton in the park on weekends." },
    { "english": "soccer", "chinese": "足球", "sentence": "They kick the soccer ball on the green grass." },
    { "english": "football", "chinese": "足球 / 美式足球", "sentence": "He likes to watch football games on TV." },
    { "english": "table tennis", "chinese": "桌球", "sentence": "We played table tennis after school today." },
    { "english": "ping-pong", "chinese": "桌球 / 乒乓球", "sentence": "Ping-pong is a fast and fun indoor game." },
    { "english": "golf", "chinese": "高爾夫球", "sentence": "My grandpa plays golf on Sunday mornings." },
    { "english": "dodgeball", "chinese": "躲避球", "sentence": "We play dodgeball in PE class." },
    { "english": "to use", "chinese": "使用", "sentence": "May I use your red pen, please?" },
    { "english": "the Internet", "chinese": "網路", "sentence": "We use the Internet to find information for homework." },
    { "english": "self", "chinese": "自己", "sentence": "Always be your true self and be happy." },
    { "english": "an introduction", "chinese": "一個介紹", "sentence": "Let's start the class with a short introduction." },
    { "english": "good morning", "chinese": "早安", "sentence": "I say good morning to my teacher every day." },
    { "english": "good afternoon", "chinese": "午安", "sentence": "\"Good afternoon,\" he said after lunch." },
    { "english": "good evening", "chinese": "晚上好", "sentence": "We say good evening when the sun goes down." },
    { "english": "to introduce", "chinese": "介紹", "sentence": "Let me introduce my best friend to you." },
    { "english": "myself", "chinese": "我自己", "sentence": "I made this beautiful birthday card by myself." },
    { "english": "to have", "chinese": "有", "sentence": "I have two cute dogs and one fat cat." },
    { "english": "to live", "chinese": "住", "sentence": "We live in a big city with many tall buildings." },
    { "english": "an apartment", "chinese": "住宅(公寓)的一戶", "sentence": "My family lives in a new apartment." },
    { "english": "to go to ... school", "chinese": "上學", "sentence": "I go to an elementary school near my house." },
    { "english": "favorite", "chinese": "最喜歡的", "sentence": "Pink is my favorite color." },
    { "english": "to like", "chinese": "喜歡", "sentence": "I like to eat sweet red apples." },
    { "english": "Minsheng", "chinese": "民生", "sentence": "My school is on Minsheng Road." },
    { "english": "east", "chinese": "東", "sentence": "The sun rises in the east every morning." },
    { "english": "a road", "chinese": "一條路", "sentence": "Be careful when you cross the busy road." },
    { "english": "kind", "chinese": "仁慈的", "sentence": "The kind teacher helped me with my math homework." },
    { "english": "mean", "chinese": "兇惡的", "sentence": "The mean boy took my toy away." },
    { "english": "patient", "chinese": "有耐心的", "sentence": "You have to be patient and wait in line." },
    { "english": "impatient", "chinese": "沒有耐心的", "sentence": "He was impatient because the bus was late." },
    { "english": "strange", "chinese": "奇怪的", "sentence": "I heard a strange noise in the dark room." },
    { "english": "thank you very much", "chinese": "非常謝謝你", "sentence": "Thank you very much for your help!" }
  ],

  // 第 9 批
  [
    { "english": "to play (a musical instrument)", "chinese": "演奏 / 拉 / 吹 / 彈 / 打", "sentence": "She learns to play the piano after school." },
    { "english": "musical", "chinese": "音樂的", "sentence": "We watched a great musical show yesterday." },
    { "english": "an instrument", "chinese": "一個樂器", "sentence": "The guitar is a very cool instrument." },
    { "english": "a flute", "chinese": "一支長笛", "sentence": "She plays a silver flute in the school band." },
    { "english": "a guitar", "chinese": "一把吉他", "sentence": "My brother plays a wooden guitar." },
    { "english": "a drum", "chinese": "一面鼓", "sentence": "He hits the drum very hard." },
    { "english": "a recorder", "chinese": "一支直笛", "sentence": "We learn to play a recorder in music class." },
    { "english": "a violin", "chinese": "一把小提琴", "sentence": "She plays a beautiful song on a violin." },
    { "english": "a piano", "chinese": "一架鋼琴", "sentence": "We have a big black piano at home." },
    { "english": "a trumpet", "chinese": "一支喇叭 / 小號", "sentence": "The golden trumpet makes a loud sound." },
    { "english": "me", "chinese": "我(受詞)", "sentence": "Can you help me with my math homework?" },
    { "english": "you", "chinese": "你(受詞)", "sentence": "I have a birthday gift for you." },
    { "english": "him", "chinese": "他(受詞)", "sentence": "I saw him playing basketball at the park." },
    { "english": "her", "chinese": "她(受詞)", "sentence": "I told her a very funny story." },
    { "english": "it", "chinese": "它 / 牠(受詞)", "sentence": "Look at the dog, I really like it." },
    { "english": "to hear", "chinese": "聽到 / 聽見", "sentence": "I can hear the little birds singing outside." },
    { "english": "to see", "chinese": "看到 / 看見", "sentence": "I want to see the monkeys in the zoo." },
    { "english": "us", "chinese": "我們(受詞)", "sentence": "The teacher told us a great story today." },
    { "english": "you (plural)", "chinese": "你們(受詞)", "sentence": "I want to play a fun game with you all." },
    { "english": "them", "chinese": "他們(受詞)", "sentence": "I like those red apples, let's buy them." },
    { "english": "Keelung", "chinese": "基隆", "sentence": "Keelung is a beautiful city with a big harbor." },
    { "english": "north", "chinese": "北", "sentence": "Taipei is a big city in the north of Taiwan." },
    { "english": "south", "chinese": "南", "sentence": "Kaohsiung is a warm city in the south." },
    { "english": "west", "chinese": "西", "sentence": "The sun goes down in the west every evening." },
    { "english": "a street", "chinese": "一條街", "sentence": "Be careful when you walk on a busy street." },
    { "english": "parents", "chinese": "父母們", "sentence": "I love my parents very much." },
    { "english": "comfortable", "chinese": "舒適的 / 舒服的", "sentence": "My bed is very soft and comfortable." },
    { "english": "because", "chinese": "因為", "sentence": "I am happy because today is my birthday." },
    { "english": "too", "chinese": "太", "sentence": "The hot soup is too hot to eat now." },
    { "english": "a shark", "chinese": "一隻鯊魚", "sentence": "A shark is a big fish with many sharp teeth." },
    { "english": "a cookie", "chinese": "一個餅乾", "sentence": "I want to eat a sweet chocolate cookie." },
    { "english": "dangerous", "chinese": "危險的", "sentence": "It is dangerous to play on the busy road." },
    { "english": "ice cream", "chinese": "冰淇淋", "sentence": "Vanilla ice cream is my favorite summer treat." },
    { "english": "pizza", "chinese": "披薩", "sentence": "We ordered a big cheese pizza for dinner." },
    { "english": "Coke", "chinese": "可口可樂", "sentence": "He likes to drink cold Coke with his pizza." },
    { "english": "iced-tea", "chinese": "冰茶", "sentence": "A glass of iced-tea is very good on a hot day." },
    { "english": "(a) cake", "chinese": "(一個)蛋糕", "sentence": "My mom baked a sweet cake for me." },
    { "english": "sweet", "chinese": "甜的", "sentence": "Candy and chocolate are very sweet." },
    { "english": "a lot of", "chinese": "很多", "sentence": "I have a lot of toys in my room." },
    { "english": "a few", "chinese": "幾個", "sentence": "I have a few red apples in my school bag." }
  ],

  // 第 10 批
  [
    { "english": "any", "chinese": "任何", "sentence": "Do you have any red pens in your pencil case?" },
    { "english": "to know", "chinese": "認識 / 知道", "sentence": "I want to know the answer to this math question." },
    { "english": "an answer", "chinese": "一個答案", "sentence": "Please write down an answer on your paper." },
    { "english": "an only child", "chinese": "(一位)唯一的 小孩 / 獨生子", "sentence": "He has no brothers or sisters, so he is an only child." },
    { "english": "a toy", "chinese": "一個玩具", "sentence": "The little boy is playing with a toy car." },
    { "english": "a dictionary", "chinese": "一本字典", "sentence": "Use a dictionary to look up new English words." },
    { "english": "to draw", "chinese": "(用筆)畫", "sentence": "I like to draw a beautiful picture of my family." },
    { "english": "to skate", "chinese": "溜冰", "sentence": "We go to the park to skate on weekends." },
    { "english": "to study", "chinese": "學習", "sentence": "We need to study hard for the English test." },
    { "english": "to jog", "chinese": "慢跑", "sentence": "My dad likes to jog in the park every morning." },
    { "english": "Mahjong", "chinese": "麻將", "sentence": "My grandparents play Mahjong during Chinese New Year." },
    { "english": "to sing", "chinese": "唱歌", "sentence": "The little birds love to sing in the morning." },
    { "english": "to want", "chinese": "想要", "sentence": "I want to eat a big hamburger for lunch." },
    { "english": "a video game", "chinese": "一個電動遊戲", "sentence": "He plays a video game after finishing his homework." },
    { "english": "sneakers", "chinese": "運動鞋(複數)", "sentence": "Put on your sneakers before we go running." },
    { "english": "a game", "chinese": "一個遊戲", "sentence": "Let's play a fun game together." },
    { "english": "to know how to", "chinese": "知道如何", "sentence": "Do you know how to ride a bicycle?" },
    { "english": "Chinese checkers", "chinese": "跳棋", "sentence": "Playing Chinese checkers with my friends is fun." },
    { "english": "with", "chinese": "跟", "sentence": "I like to play with my little sister." },
    { "english": "together", "chinese": "在一起", "sentence": "We can sing and dance together." },
    { "english": "grandparents", "chinese": "祖父母", "sentence": "We visit our grandparents on Sunday afternoons." },
    { "english": "to understand", "chinese": "了解 / 懂 / 明白", "sentence": "I don't understand this math question, can you help me?" },
    { "english": "to mean", "chinese": "...的意思是", "sentence": "What does this English word mean?" },
    { "english": "international", "chinese": "國際的", "sentence": "English is a very useful international language." },
    { "english": "a language", "chinese": "一種語言", "sentence": "She wants to learn a new language." },
    { "english": "How many", "chinese": "多少 / 幾個", "sentence": "How many apples are there on the table?" },
    { "english": "a piece", "chinese": "一片 / 一塊", "sentence": "I want to eat a piece of chocolate cake." },
    { "english": "to be", "chinese": "當", "sentence": "I want to be a great teacher when I grow up." },
    { "english": "next", "chinese": "下一個", "sentence": "Who is the next student to read the story?" },
    { "english": "many", "chinese": "很多(複數的)", "sentence": "There are many interesting books in the library." },
    { "english": "to kiss", "chinese": "親吻", "sentence": "The mother likes to kiss her baby goodnight." },
    { "english": "to teach", "chinese": "教", "sentence": "The music teacher will teach us a new song today." },
    { "english": "to wash", "chinese": "洗", "sentence": "Remember to wash your hands before eating dinner." },
    { "english": "to fix", "chinese": "修理", "sentence": "My smart dad knows how to fix the broken toy." },
    { "english": "to brush", "chinese": "刷 / 梳", "sentence": "You should brush your teeth every morning and night." },
    { "english": "How much", "chinese": "多少(不可數)", "sentence": "How much milk do you want to drink?" },
    { "english": "much", "chinese": "很多(不可數)", "sentence": "We don't have much time left before the bus comes." },
    { "english": "to chase", "chinese": "追", "sentence": "Dogs sometimes like to chase cute little cats." },
    { "english": "to change", "chinese": "改變 / 換", "sentence": "The traffic light will change to red soon." },
    { "english": "to practice", "chinese": "練習", "sentence": "You must practice playing the piano every day." }
  ],

  // 第 11 批
  [
    { "english": "o'clock", "chinese": "...點鐘", "sentence": "It is seven o'clock, time to get up." },
    { "english": "mine", "chinese": "我的+noun", "sentence": "This blue pencil is mine." },
    { "english": "yours", "chinese": "你的+noun", "sentence": "Is this red eraser yours?" },
    { "english": "his", "chinese": "他的+noun", "sentence": "The big robot toy is his." },
    { "english": "hers", "chinese": "她的+noun", "sentence": "That beautiful doll on the desk is hers." },
    { "english": "its", "chinese": "它的 / 牠的+noun", "sentence": "The dog is playing with its toy." },
    { "english": "polite", "chinese": "有禮貌的", "sentence": "He is a polite boy and always says thank you." },
    { "english": "a lady", "chinese": "一位女士", "sentence": "A kind lady helped me open the heavy door." },
    { "english": "rude", "chinese": "粗魯的", "sentence": "It is rude to talk loudly in the library." },
    { "english": "impolite", "chinese": "沒有禮貌的", "sentence": "It is impolite to point your finger at people." },
    { "english": "generous", "chinese": "慷慨的 / 大方的", "sentence": "My generous friend shared his cookies with me." },
    { "english": "greedy", "chinese": "貪心的", "sentence": "The greedy dog wanted to eat all the meat." },
    { "english": "a guy", "chinese": "一位男生", "sentence": "That tall guy over there is my uncle." },
    { "english": "Mr.", "chinese": "先生", "sentence": "Mr. Lin is our fun math teacher." },
    { "english": "Mrs.", "chinese": "太太", "sentence": "Mrs. Wang makes the best apple pie." },
    { "english": "Miss", "chinese": "小姐", "sentence": "Miss Chen teaches us how to sing beautiful songs." },
    { "english": "Ms.", "chinese": "女士", "sentence": "Ms. Lee is our new English teacher." },
    { "english": "ours", "chinese": "我們的+noun", "sentence": "This big and clean classroom is ours." },
    { "english": "yours (plural)", "chinese": "你們的+noun", "sentence": "Are these colorful notebooks yours?" },
    { "english": "theirs", "chinese": "他們的+noun", "sentence": "That big house with a garden is theirs." },
    { "english": "to wake up", "chinese": "醒來", "sentence": "I usually wake up early on Mondays." },
    { "english": "usually", "chinese": "通常", "sentence": "I usually have milk and bread for breakfast." },
    { "english": "in the morning", "chinese": "在早上", "sentence": "The sun shines brightly in the morning." },
    { "english": "in the afternoon", "chinese": "在下午", "sentence": "We play basketball in the afternoon." },
    { "english": "in the evening", "chinese": "在傍晚", "sentence": "My family watches TV in the evening." },
    { "english": "at night", "chinese": "在晚上", "sentence": "The sky is dark and full of stars at night." },
    { "english": "to work", "chinese": "工作", "sentence": "My mother goes to work by train every day." },
    { "english": "to get to (a place)", "chinese": "到達(一個地方)", "sentence": "How do you get to the park from here?" },
    { "english": "to walk", "chinese": "走路", "sentence": "I like to walk to school with my sister." },
    { "english": "to take (a bus)", "chinese": "搭(公車)", "sentence": "We have to take a bus to the museum." },
    { "english": "to take (ST/SB to SP)", "chinese": "帶去", "sentence": "My dad will take me to the zoo today." },
    { "english": "a taxi", "chinese": "一輛計程車", "sentence": "They took a yellow taxi to the station." },
    { "english": "the MRT", "chinese": "(台灣的)捷運", "sentence": "Taking the MRT is very fast and convenient." },
    { "english": "a school bus", "chinese": "一輛校車", "sentence": "The yellow school bus comes at seven in the morning." },
    { "english": "a motorcycle", "chinese": "一輛摩托車", "sentence": "My father rides a motorcycle to the office." },
    { "english": "a bus", "chinese": "一輛公車", "sentence": "We waited for a long time to catch a bus." },
    { "english": "to get up", "chinese": "起來", "sentence": "You need to get up now or you will be late." },
    { "english": "a meal", "chinese": "一個餐 / 一頓飯", "sentence": "Breakfast is the most important meal of the day." },
    { "english": "breakfast", "chinese": "早餐", "sentence": "I eat a yummy egg for breakfast every day." },
    { "english": "lunch", "chinese": "午餐", "sentence": "We have rice and green vegetables for lunch." }
  ],

  // 第 12 批
  [
    { "english": "dinner", "chinese": "晚餐", "sentence": "We have a big dinner together at six o'clock." },
    { "english": "(a) dessert", "chinese": "(一個)飯後甜點", "sentence": "I like to eat sweet ice cream for dessert." },
    { "english": "a snack", "chinese": "一個點心", "sentence": "I usually eat a small snack after school." },
    { "english": "weather", "chinese": "天氣", "sentence": "The weather is very nice and warm today." },
    { "english": "warm", "chinese": "溫暖的", "sentence": "Spring is a beautiful and warm season." },
    { "english": "cool", "chinese": "涼爽的", "sentence": "The wind feels very cool in autumn." },
    { "english": "sunny", "chinese": "晴天", "sentence": "We can play baseball outside on a sunny day." },
    { "english": "cloudy", "chinese": "多雲的", "sentence": "It is cloudy today, we might need an umbrella." },
    { "english": "rainy", "chinese": "多雨的", "sentence": "I stay at home and read books on a rainy day." },
    { "english": "raining", "chinese": "正在下雨", "sentence": "Look outside, it is raining now!" },
    { "english": "beautiful", "chinese": "美麗的", "sentence": "She drew a beautiful picture of a pink flower." },
    { "english": "a typhoon", "chinese": "一個颱風", "sentence": "A strong typhoon is coming to Taiwan." },
    { "english": "windy", "chinese": "多風的", "sentence": "It is very windy, please hold your hat!" },
    { "english": "as adj as", "chinese": "像什麼一樣", "sentence": "My older brother is as tall as my dad." },
    { "english": "a television", "chinese": "一台電視", "sentence": "We bought a new television for the living room." },
    { "english": "brave", "chinese": "勇敢的", "sentence": "The brave firefighter saved the little cat." },
    { "english": "to come", "chinese": "來", "sentence": "Please come to my birthday party on Sunday." },
    { "english": "on my way", "chinese": "去什麼地方的路上", "sentence": "I am on my way to school now." },
    { "english": "McDonald's", "chinese": "麥當勞", "sentence": "We had yummy burgers and fries at McDonald's." },
    { "english": "yourself", "chinese": "你自己", "sentence": "You can draw the picture by yourself." },
    { "english": "himself", "chinese": "他自己", "sentence": "He made the toy car by himself." },
    { "english": "herself", "chinese": "她自己", "sentence": "The little girl dressed herself this morning." },
    { "english": "itself", "chinese": "它自己", "sentence": "The cute cat is washing itself." },
    { "english": "ourselves", "chinese": "我們自己", "sentence": "We can finish the homework by ourselves." },
    { "english": "yourselves", "chinese": "你們自己", "sentence": "Please help yourselves to the sweet cookies." },
    { "english": "themselves", "chinese": "他們自己", "sentence": "They cleaned the big classroom by themselves." },
    { "english": "ever", "chinese": "有時候", "sentence": "Do you ever play tennis after school?" },
    { "english": "always", "chinese": "總是", "sentence": "I always brush my teeth before going to bed." },
    { "english": "often", "chinese": "常常", "sentence": "We often play basketball in the park." },
    { "english": "sometimes", "chinese": "有時候", "sentence": "I sometimes help my mom cook dinner." },
    { "english": "seldom", "chinese": "很少", "sentence": "He seldom eats candy because it is bad for teeth." },
    { "english": "rarely", "chinese": "很少", "sentence": "It rarely snows in our beautiful city." },
    { "english": "never", "chinese": "從不 / 都沒有", "sentence": "I never go to bed late on a school night." },
    { "english": "before", "chinese": "在...之前", "sentence": "Please wash your hands before eating dinner." },
    { "english": "to review", "chinese": "複習", "sentence": "We need to review English words for the test." },
    { "english": "to hug", "chinese": "擁抱", "sentence": "I like to hug my mom before I go to sleep." },
    { "english": "to start", "chinese": "開始", "sentence": "The spelling game will start in one minute." },
    { "english": "to buy", "chinese": "買", "sentence": "We went to the supermarket to buy some apples." },
    { "english": "ninth (9th)", "chinese": "第九", "sentence": "They are 9th grade students." },
    { "english": "tenth (10th)", "chinese": "第十", "sentence": "My home is on the 10th floor." }
  ],

  // 第 13 批
  [
    { "english": "eleventh (11th)", "chinese": "第十一", "sentence": "November is the 11th month of the year." },
    { "english": "twelfth (12th)", "chinese": "第十二", "sentence": "December is the 12th month of the year." },
    { "english": "thirteenth (13th)", "chinese": "第十三", "sentence": "Today is my brother's 13th birthday." },
    { "english": "fourteenth (14th)", "chinese": "第十四", "sentence": "Valentine's Day is on February 14th." },
    { "english": "fifteenth (15th)", "chinese": "第十五", "sentence": "We will go to the zoo on the 15th of May." },
    { "english": "sixteenth (16th)", "chinese": "第十六", "sentence": "She is the 16th student in the line." },
    { "english": "seventeenth (17th)", "chinese": "第十七", "sentence": "He sits on the 17th seat in the classroom." },
    { "english": "eighteenth (18th)", "chinese": "第十八", "sentence": "My cousin just had his 18th birthday party." },
    { "english": "nineteenth (19th)", "chinese": "第十九", "sentence": "The 19th book on the shelf is mine." },
    { "english": "twentieth (20th)", "chinese": "第二十", "sentence": "Today is the 20th day of the month." },
    { "english": "twenty-first (21st)", "chinese": "第二十一", "sentence": "March 21st is a beautiful spring day." },
    { "english": "twenty-second (22nd)", "chinese": "第二十二", "sentence": "My house is on the 22nd street." },
    { "english": "twenty-third (23rd)", "chinese": "第二十三", "sentence": "He won the 23rd prize in the game." },
    { "english": "twenty-fourth (24th)", "chinese": "第二十四", "sentence": "Christmas Eve is on December 24th." },
    { "english": "twenty-fifth (25th)", "chinese": "第二十五", "sentence": "Christmas Day is on December 25th." },
    { "english": "twenty-sixth (26th)", "chinese": "第二十六", "sentence": "The letter Z is the 26th letter of the alphabet." },
    { "english": "twenty-seventh (27th)", "chinese": "第二十七", "sentence": "Her birthday is on the 27th of August." },
    { "english": "twenty-eighth (28th)", "chinese": "第二十八", "sentence": "February usually has 28 days." },
    { "english": "twenty-ninth (29th)", "chinese": "第二十九", "sentence": "A leap year has a 29th day in February." },
    { "english": "thirtieth (30th)", "chinese": "第三十", "sentence": "Tomorrow is the 30th of April." },
    { "english": "thirty-first (31st)", "chinese": "第三十一", "sentence": "Halloween is on October 31st." },
    { "english": "a birthday", "chinese": "一個生日", "sentence": "I want a big chocolate cake for my birthday." }
  ]
];

// 把上述所有的陣列合併成一個一維陣列 (共 492 個單字)
const wordList = allBatches.flat();
